print('\nListing 2.12: Using Input')
print('Please enter some text: ')
x = input()
print('Text entered:', x)
print('Type:', type(x))

print('\nListing 2.12: Adding Integers')
print('Please enter an integer value:')
x = input()
print('Please enter another integer value:')
y = input()
num1 = int(x)
num2 = int(y)
print(num1, '+', num2, '=', num1 + num2)

print('\nListing 2.14: Adding Integers 2')
print('Assign x and y and use command input.')
x = input('Please enter an integer value: ')
y = input('Please enter another integer value: ')
num1 = int(x)
num2 = int(y)
print(num1, '+', num2, '=', num1 + num2)

print('\nListing 2.15: Adding Integers 3')
print('Directly assigns x and y using input to num1 and num2 respectively.')
num1 = int(input('Please enter an integer value: '))
num2 = int(input('Please enter another integer value: '))
print(num1, '+', num2, '=', num1 + num2)
